### ISSUE TITLE
https://acme.castle.cloud/acme/terms_of_service.pdf does not exist

### ISSUE THREAD

**Issue by DDvO** [polhenarejos/acme_email#17]
The link in the below output is broken:
```
Please read the Terms of Service at
https://acme.castle.cloud/acme/terms_of_service.pdf. You must agree in order to
register with the ACME server. Do you agree?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: 
```

**Comment by polhenarejos** [comment]
Should be fixed now.

**Comment by DDvO** [comment]
No, https://acme.castle.cloud/acme/terms_of_service.pdf still does not exist.
`ERROR 404: Not Found.`

**Comment by DDvO** [comment]
> Should be fixed now.

Not really.
I would have re-opened the issue, but cannot :(
